### PR TITLE
Add integer support

### PR DESCRIPTION
**Pull request by davidalo**

### CODE REVIEW

**Comment by kgabis** [comment]
This has been brought up before:
https://github.com/kgabis/parson/issues/160

Also, someone has already implemented it:
https://github.com/kgabis/parson/pull/44

**Comment by davidalo** [comment]
I saw, but it has not been implemented and it is a necessary feature when serializing JSON I think @kgabis .

**Comment by kgabis** [comment]
Can you describe what problem it solves?

**Comment by davidalo** [comment]
Sure. It's because some HTTP servers does not allow floating points in integer fields, so they can accept:
``` 
{"myfield": 3}
```
But not:
```
{"myfield": 3.0}
``` 
In addition, I have no option to manage `FLOAT_FORMAT` (see #170) so I can not control the length of this field. Furthermore, I am interested in combining both types in some requests, so changing the format for the whole module is not an option.

**Comment by kgabis** [comment]
```
~ cat test.c
#include <stdio.h>

#include "parson.h"

int main() {
    JSON_Value *root_value = json_value_init_object();
    JSON_Object *root_object = json_value_get_object(root_value);
    json_object_set_number(root_object, "myfield", 3);
    char *serialized_string = json_serialize_to_string(root_value);
    puts(serialized_string);
    json_free_serialized_string(serialized_string);
    json_value_free(root_value);
}
~ gcc test.c parson.c -o test
~ ./test
{"myfield":3}
```
If numbers have no decimal part then they should be serialised without it or am I missing something?
Regarding #170 I might add it as a functional call that sets a global value rather than a compile time constant.

**Comment by davidalo** [comment]
It depends on your underlying architecture, I am working with embedded devices which use their own `std` implementation and their behavior can differ from a OS-based machine. I can send you some examples if you want.  That's why I purpose both changes (this and #170). 

About #170, it's ok, you're rigth. I can refactor the PR to be allow configuration at run time instead of compile time. I purposed it in that way just modify as less as possible your code

**Comment by kgabis** [comment]
So if I understand correctly: some non-standard "std"s print decimal places when using %g specifier even when they shouldn't and some HTTP servers don't accept valid JSON when it contains numbers with decimal places?

**Comment by davidalo** [comment]
Yes, that is what I mean. Another option could be configure the number specifier before each `_set_number` operation at runtime.

**Comment by kgabis** [comment]
It all sounds like a hack to fix a very specific issue that should be fixed elsewhere. I won't introduce another number type just for that.

Maybe it would be better to check if number has a fractional part and if it doesn't use %d format?
```c
if (num == (int)num)) {
    written = sprintf(num_buf, "%d", (int)num);
} else {
    written = sprintf(num_buf, FLOAT_FORMAT, num);
}
```

**Comment by davidalo** [comment]
I would have to test it to confirm you it works as expected. Anyway, float numbers with `.0` as decimal will be formatted as integers instead of float, won't they? 

For example, with this solution `100.0` will be formatted as `100` instead of `100.0`.

**Comment by kgabis** [comment]
I disagree, parson covers all data types specified by JSON standard so I don't see a reason to add more because some http servers don't accept valid JSON. I might add customisable float format though. Anyway, you are free to fork parson and add an integer type to it.

**Comment by davidalo** [comment]
I understand you, but I don't see any problem in giving more flexibility to a great library. Anyway, thanks for your time.

**Pull request closed without merging**
