### PR TITLE
Added fsync to force flushing of file to disk.

### PR DESCRIPTION
**Pull request by mrkozmic**
Added fsync to force flushing of file to disk.

### CODE REVIEW

**Comment by kgabis** [comment]
Merging this would break builds on non-POSIX systems (because unistd.h is POSIX-specific). Is there a portable way of accomplishing this without using ifdefs?

**Comment by mrkozmic** [comment]
The only alternative as I know is O_SYNC flag used with open()...

**Comment by kgabis** [comment]
Anyway I'm not sure if fsyncing everytime is a good idea, there's a reason it's not being done by default. Also, ```json_serialize_to_file``` and ```json_serialize_to_file_pretty``` should be treated as utility functions and I'm not sure if they should've ended up in the API. It's impossible for them to fit every use case so if you really need to make sure that files get synced you should probably write your own write-to-file function.

**Comment by mrkozmic** [comment]
What about an user defined callback function or a macro before fclose? 
#define SYNC(fd) fsync(fileno(fd))

The reason I would like to fsync is that I use parson on an embedded platform with flash hence not very frequent writing to the flash. 

PS whould be nice with support for custom callbacks or macros for debugging and logging

**Comment by kgabis** [comment]
I understand that in some cases fsync might be desirable, however I don't think it should influence API in any way. I suggest writing a custom string-to-file function for that.

What do you mean by "custom callbacks or macros for debugging and logging"? Could you provide some examples?

**Comment by mrkozmic** [comment]
Take the internal function read_file() called by json_parse_file()  as an example. It returns NULL when one of four errors occur. Consequently json_parse_file also returns NULL, but what was the reason for failing? 
I show only part of the read_file() function here:

static char * read_file(const char * filename) {
    FILE *fp = fopen(filename, "r");
    size_t file_size;
    long pos;
    char *file_contents;
    if (!fp) {
        /*one of the below could be used. read_file_fopen_failed is an enum*/
        /* enums must be defined in parson.h */
        /* the same could be done for logging. Alternatively multi level debugging could be implemented to cover logging*/ 
        /*the two first are callbacks*/
        if(debug)
        {
            debug(read_file_fopen_failed);
            debug("read_file_fopen_failed"); /*using plain text*/
        }
        /*these two are macros*/
        DEBUG(read_file_fopen_failed);
        DEBUG("read_file_fopen_failed");
        return NULL; 
    }

And a function to set the callback:
json_set_debug_callback(void (*debug)(enum or char*, etc...))

There could be different callback functions with different levels of information. Eg. parsing functions could output debug info with parent object name, values, array index, etc...

**Comment by kgabis** [comment]
I think it would be better to add a function like ```json_parse_file2(const char *filename, JSON_Parse_Error *out_error)``` where ```JSON_Parse_Error``` would hold some error code and an offset to a place of failure (in case opening a file succeeded but json was invalid).

**Comment by mrkozmic** [comment]
That will definitely improve debugging.
By the way, you are already using callback functions:
void json_set_allocation_functions(JSON_Malloc_Function malloc_fun, JSON_Free_Function free_fun);

**Comment by kgabis** [comment]
Using function pointers for memory allocation is one thing. But using them for debugging seems a bit impractical. It would just tell you that something somewhere failed, which is not very helpful.

**Pull request closed without merging**
