### PR TITLE
Refactor float format to make it configurable at compile time

### PR DESCRIPTION
**Pull request by davidalo**

### CODE REVIEW

**Comment by bawilless** [comment]
For what it's worth, I would love to be able to format floats/doubles when using the parson library to create json.

**Comment by davidalo** [comment]
Maybe a run-time solution can be a better option. Something like:

```cpp
#define FLOAT_FORMAT "%1.17g"

const char *number_format = FLOAT_FORMAT;

void json_set_number_format(const char *fmt) {
   number_format = fmt;
}

static int json_serialize_to_buffer_r(...){ 
    ...
   written = sprintf(num_buf, number_format, num);
   ...
}
```

This will allow us to configure the number format for our purposes. What do you think @bawilless  @kgabis ?

**Comment by sgh** [comment]
The number of decimals must be per number because sometimes you want some numbers with 2 decimals and others with another number of decimals.

**Comment by sgh** [comment]
Are someone working on this? - and can we agree on some kind of solution that - if implemented - can be merged?

**Comment by kgabis** [comment]
This was addressed in af848c27b467afff371aa22af9da2f3e1e15692a.

**Pull request closed without merging**
