### PR TITLE
Adds travis support, with README badge

### PR DESCRIPTION
**Pull request by 7heo**
Go to https://travis-ci.org/profile/kgabis in order to enable the travis testing on this repository. Once this is done, every PR (and direct pushes too) will be tested automatically when it is open. You will also have to authorize travis as an oauth app for your profile.

*Note: If you merge this PR after #76, you will need to append `make tests` in the `.travis.yml` file. If you merge it before, you will need to append that line in #76.*

### CODE REVIEW

**Comment by kgabis** [comment]
I don't see a good reason to add this change. It's a small project and I test every PR myself, having a green badge in readme doesn't really add much value. And  seeing if parson builds is probably the least time consuming part of accepting a PR. I might be missing something though, so feel free to explain your view.

**Comment by 7heo** [comment]
Pretty simple. What can be automated shall be automated. No matter how, you can never be on average faster than travis, because that would require you to instantly start testing the PR when it is submitted. The results of the tests are not only for you, but for the people sending the PRs too. If they didn't bother to run the tests, and send the PR, they will see that their patch is broken before you tell them.

Also testing with the default make rule is semantically incorrect; as it will break many distribution tools, expecting to have tests in a separate rule (but that's in another PR).

**Comment by kgabis** [comment]
I disagree, sometimes the cost of automating something is higher than the value it provides (see home IoT). And the only thing it automates is a one line command. I don't know what travis-ci is, if it will exist in few years, and what it will do with all the permissions it requires. And a PR not building has never been an issue so far. I'll close this PR because I really don't see a reason to merge it. Also, sorry for not addressing you other PR so far, I'll take a look at it when I've got a spare moment.

**Comment by solvingj** [comment]
I think it's worth pointing out that this ticket and the one for CMake (#92) are trying to indicate to you that people really like your library and it is successful.  Specifically, it's not just people experimenting with toy projects where indeed, they could just copy and compile your lib on it's own at that point-in-time. This has been the status-quo for small c projects for some time.  Now, people are wanting to incorporate `parson` into a larger ecosystem, which includes larger projects like Microsoft IOT Edge SDK, and projects which use modern builds systems and automated pipelines (Cmake, TravisCI, Appveyor, Etc).  The ecosystem prefers that all the foundational libraries like parson use semantic versioning, and CI to run the tests and create periodic versioned releases. Along with the Cmake file, these things represent a somewhat common "API" between cross-platform OSS C and C++ projects which is emerging. 

It's understandable if you're not interested in such an ecosystem, and indeed its not trivial to learn all these things.  However, it was worth pointing out why these questions are coming up, and pointing out that they have related motivations.

**Comment by 7heo** [comment]
@solvingj I'd like to chime in on this and say that following the comments from kgabis, I went for a different solution. So while you are right that the original issue is a sign of interest in this library, it is not worth fighting for. I'd also suggest for your own sake not to try to educate people on internet (see https://www.xkcd.com/386/) as anyway, most people will only learn from their own mistakes (but that's merely a suggestion). I for one have no problem letting kgabis fail slowly, and learn as a result; rather than waste my time trying to change everyone for the better. This is not a fight worth picking.

**Comment by kgabis** [comment]
As I said previously, I don't see a good reason to add travis support and there's no obvious benefit gained from using it. I can easily manage incoming pull requests and adding some third party tool seems like an overkill. Please correct me if I'm wrong.
@solvingj Instead of periodic automated releases I'd rather have a separate branch for each release because it works quite nicely with git submodules (afaik there's no way to pin submodule to specific git tag). But on the other hand I don't really make releases because I'm quite consistent in not breaking the API. Having an arbitrary number that gets incremented with each change seems quite unnecessary and it doesn't seem to add much value. I understand it fits in *some* workflows, but I don't think it's a good enough reason to have it. Again, I might be missing something, but right now I'm not convinced parson should have cmake/travis/appveyor support.
@7heo Your comment is unnecessary and doesn't add anything to this discussion, it will be removed tomorrow.

**Comment by solvingj** [comment]
Indeed releases would only be needed for API changes and bugfixes.  I should have said that instead.  

In any case, I appreciate your consideration.  Many maintainers randomly abandon projects and completely ignore community feedback.  I think the important thing is that most of the reasons which do exist have no been explained to a reasonable degree within the various github issues.  We've had an open discussion, and the maintainer has made a decisions that the benefits are insufficient to justify the additional complexity.  It seems to me that's how the process is supposed to work.  Thanks again.  If you change your mind in the future, we'll be more than happy to give a crash course on the relevant CI and Cmake stuff.

**Pull request closed without merging**
