### PR TITLE
Expose a new API for encoding C string.

### PR DESCRIPTION
**Pull request by t-k-**
In my use case,  I need a lower level API to encode C string directly to JSON string.

### CODE REVIEW

**Comment by kgabis** [comment]
Could you provide an example of an use case for this function?

**Comment by t-k-** [comment]
When efficiency matters (in my case a search engine), one can use `sprintf` to generate JSON string, without constructing a JSON_Value. 

In my case, the format string looks something like below

```
"hits": [
{ "docID": %u, "url": %s, "snippet": %s}
 ...
]
```

Where I know things to put after "docID" or "url" does not need to be JSON encoded/escaped, while the string after "snippet" possibly needs to be encoded/escaped. Thus `sprintf` plus calling a single JSON string encoded/escape API is sufficient for a search engine to generate search results, and it is efficient.

Yes, perhaps I can use parson to generate JSON by constructing a JSON_Value and do json_serialize_* to build this string, but this is not as direct as what a `sprintf` is doing.

**Comment by kgabis** [comment]
I don't think this belongs in the API because it only solves a very specific use case. Wouldn't it be easier to just copy json_serialize_string from parson.c into your code and use it that way? I might be wrong however I don't want to extend the API unless I see a good reason to do so.

**Comment by t-k-** [comment]
Thank you for your comment, I am submit this pr just hoping my own change can be ultilized by others. Anyway, I am switching from YAJL to Parson because YAJL has memory leaks, and from my opinion, Parson has a much better and simpler design just by looking at the code. Thank you for creating Parson.

**Comment by kgabis** [comment]
I'm glad you like it, hopefully it will meet your requirements :)

**Pull request closed without merging**
